/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pvtcnstrcttest;

public class App {

  public static void main(String[] args) {
    
    try {
      System.out.println(SomeSingleton.getInstance().someMethod());
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }

  }
}
